services:
  app:
    build:
      context: .
      dockerfile: python.Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - ./server:/app/server
      - ./data:/app/data
    environment:
      - PORT=8888
